Support in-browser uses
sindresorhus/ansi-escapes pull request #31
Opened 2023-02-27 09:01 UTC by Reverier-Xu

Hi, thank you for your awesome work!

I'd like to developing a fake shell based on xterm.js in frontend. I found that Vite dev server gives a warning like that:

```
Module "node:process" has been externalized for browser compatibility. Cannot access "node:process.env" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
get @ browser-external:node:process:9
```

The `TERM_PROGRAM` env variable also does not exist in browser: 

```
TypeError: Cannot read properties of undefined (reading 'TERM_PROGRAM')
```

According to the [Node | Webpack](https://webpack.js.org/configuration/node/#node-process) documentation, the webpack can make polyfills for different node functions, but it appears as the node.process is a "mock";

> "mock": Provide a mock that implements the expected interface but has little or no functionality.

So I added some code to judge the current running environment in advance, and moved some code related to Node to conditional judgment.

2023-03-15 11:39 UTC, countfak commented
Hi, is this getting merged soon by any chance?

2023-03-15 12:07 UTC, Reverier-Xu commented
> Hi, is this getting merged soon by any chance?

I published an alternative package [isomorphic-ansi-escapes](https://www.npmjs.com/package/isomorphic-ansi-escapes) to temporarily replace this. You can use it before this pr gets merged.

2023-03-15 12:17 UTC, countfak commented
> 

Hi, thank you!

2023-03-16 06:19 UTC, sindresorhus requested changes

2023-03-16 06:19 UTC, sindresorhus commented on index.js
> +const cwdFunc = cwdFunc_;
Would be simpler to just use a ternary for each of these. Then you don't need all this reassignment.

2023-03-16 06:19 UTC, sindresorhus commented on index.js
> +let platform_ = 'browser';
Just make a `isWindows` variable instead. As that's what `platform` is used for.

2023-03-16 06:19 UTC, sindresorhus commented on index.js
> +let cwdFunc_ = () => {
```suggestion
let cwdFunction_ = () => {
```

2023-03-16 06:19 UTC, sindresorhus commented on index.js
> +	throw new Error('NodeJS.Process.cwd() doesn\'t work in Browser.');
```suggestion
	throw new Error('`process.cwd()` only works in Node.js, not the browser.');
```

2023-03-16 06:20 UTC, sindresorhus commented
Maybe also mention in the readme that it can be used in the browser with xterm.js

2023-03-16 08:05 UTC, merged

2023-03-16 14:05 UTC, countfak commented
You're great, thanks.